name: Deploy app
on:
  push:
    branches: 
      - main
      - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest

      - name: Deploy to staging
        if: github.ref == 'refs/heads/staging'
        working-directory: ./truecable-discount-app-staging
        env:
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY2 }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
        run: shopify app deploy -f --source-control-url "$COMMIT_URL"

      - name: Deploy to main
        if: github.ref == 'refs/heads/main'
        working-directory: ./truecable-discount-app-main
        env:
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
        run: shopify app deploy -f --source-control-url "$COMMIT_URL"
